### PR TITLE
Remove TPH

### PR DESCRIPTION
**Pull request by gmemstr**

### CODE REVIEW

**Comment by ljosberinn** [comment]
Context: 
- TPH fosters a 4chan-like trolling atmosphere
- TBH is the _only_ server in all of these that disallow linking other dev-related discords
- whilst discussing ^ in ModMail anonymously, one of their admins actively came over to /r/webdev & web_design to promote TPH, knowing that I just got warned on their server for supposedly doing exactly that

**Comment by ljosberinn** [comment]
After talking with said admin some more, we resolved the situation on a friendly basis. If someone wants to reintroduce the server, so be it.

**Comment by pqt** [comment]
I'm always so surprised to see so much universal hatred for TPH floating around the dev communities.

**Comment by ljosberinn** [comment]
What are you referring to? Hatred is a strong word, I don't think anyone in here `hates` a community, just because they've made bad experiences.

Personally, I'm expecting a helpful & friendly environment, and that was not what I found.

**Pull request merged**
